repos:
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black-jupyter
      language_version: python3.9